# Task - 6 (Numpy)

In [ ]:
# Question :- 01
# Statement :- Arrays

import numpy
def arrays(arr):
  return numpy.array(arr[::-1], float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [ ]:
# Question :- 02
# Statement :- Shape and Reshape

import numpy
arr = list(map(int, input().split()))
print(numpy.reshape(arr, (3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Question :- 03
# Statement :- Transpose and Flatten

import numpy as np
lst = []
n, m = list(map(int, input().split()))
for i in range(n):
  lst.append([input().strip().split()])

arr = np.reshape(np.array(lst, int), (n,m))
print(np.transpose(arr))
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
# Question :- 04
# Statement :- Concatenate

import numpy
n = list(map(int, input().split()))
A = numpy.array([input().split() for i in range(n[0])], int)
B = numpy.array([input().split() for i in range(n[1])], int)
print(numpy.concatenate((A, B), axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [ ]:
# Question :- 05
# Statement :- Zeros and Ones

import numpy
n = list(map(int, input().split()))
print(numpy.zeros((n), dtype=numpy.int))
print(numpy.ones((n), dtype=numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [ ]:
# Question :- 06
# Statement :- Eye and Identity

import numpy
numpy.set_printoptions
N, M = map(int, input().split())
print(numpy.eye(N, M, k=0))

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Question :- 07
# Statement :- Array Mathematics

import numpy
N, M = map(int, input().split())
A = numpy.array([input().split() for i in range(N)], int)
B = numpy.array([input().split()], int)
print(numpy.add(A, B))
print(numpy.subtract(A, B))
print(numpy.multiply(A, B))
print(A//B)
print(numpy.mod(A, B))
print(numpy.power(A, B))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [ ]:
# Question :- 08
# Statement :- Floor, Ceil and Rint

import numpy
numpy.set_printoptions
arr = numpy.array(input().strip().split(), float)
print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [ ]:
# Question :- 09
# Statement :- Sum and Prod

import numpy
N, M = map(int,input().split())
arr = numpy.array([input().split() for i in range(N)], int)
print(numpy.prod(numpy.sum(arr, axis=0)))

2 2
1 2
3 4
24


In [1]:
# Question :- 10
# Statement :- Min and Max

import numpy
N, M = map(int, input().split())
arr = numpy.array([input().split() for i in range(N)], int)
print(numpy.max(numpy.min(arr, axis=1)))

4 2
2 5
3 7
1 3
4 0
3


In [2]:
# Question :- 11
# Statement :- Mean, Var, and Std

import numpy
N, M = map(int, input().split())
arr = numpy.array([input().split() for i in range(N)], int)
print(numpy.mean(arr, axis=1))
print(numpy.var(arr, axis=0))
print(round(numpy.std(arr, axis=None), 11))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


In [5]:
# Question :- 12
# Statement :- Dot and Cross

import numpy
N = int(input())
A = numpy.array([input().split() for i in range(N)], int)
B = numpy.array([input().split() for i in range(N)], int)
print(numpy.dot(A, B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [6]:
# Question :- 13
# Statement :- Inner and Outer

import numpy
A = numpy.array(input().split(), int)
B = numpy.array(input().split(), int)
print(numpy.inner(A, B))
print(numpy.outer(A, B))

0 1
2 3
3
[[0 0]
 [2 3]]


In [7]:
# Question :- 14
# Statement :- Polynomials

import numpy
print(numpy.polyval(numpy.array(input().split(), float), float(input())))

1.1 2 3
0
3.0


In [8]:
# Question :- 15
# Statement :- Linear algebra

import numpy
numpy.set_printoptions
n = int(input())
arr = numpy.array([input().split() for i in range(N)], float)
print(numpy.linalg.det(arr))

2
1.1 1.1
1.1 1.1
0.0
